name: Java CI

on:
  push:
    branches:
      - "!main"   # run on any branch except main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and run tests with Maven
        run: mvn -B clean test

  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: "Automated PR from ${{ github.ref_name }}"
          body: "This PR was automatically created after tests passed."
          commit-message: "Auto PR from ${{ github.ref_name }}"
          labels: automated

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
