name: Java Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review    # ✅ adds comments directly to PR
          checkstyle_config: google_checks.xml

  spotbugs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.7.3.0:check
